# Config file for automatic testing at travis-ci.org

language: python

python:
    - 2.7
    - 3.2

virtualenv:
    system_site_packages: true

before_install:
    - sudo apt-get update
    - sudo apt-get install $PYTHON-setuptools
    - sudo apt-get install $PYTHON-numpy
    - sudo apt-get install $PYTHON-scipy
    - sudo apt-get install $PYTHON-nose
    - sudo pip install numpy
    - sudo pip install scipy

install:
    - sudo $PYTHON setup.py install

script: nosetests tests
