# Config file for automatic testing at travis-ci.org

language: python
sudo: false

python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - 3.6

# test minium required and current version of scipy
env:
    - SCIPY_VERSION=0.15
    - SCIPY_VERSION=0.18.1

matrix:
    exclude:
        -  python: 3.3
           env: SCIPY_VERSION=0.18.1
        -  python: 3.5
           env: SCIPY_VERSION=0.15
        -  python: 3.6
           env: SCIPY_VERSION=0.15

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a

install:
    - if [[ $SCIPY_VERSION == 0.15 ]]; then conda create -q -n test_env python=$TRAVIS_PYTHON_VERSION numpy scipy=$SCIPY_VERSION libgfortran=1 pandas matplotlib nose; fi
    - if [[ $SCIPY_VERSION != 0.15 ]]; then conda create -q -n test_env python=$TRAVIS_PYTHON_VERSION numpy scipy=$SCIPY_VERSION pandas matplotlib nose; fi
    - source activate test_env
    - pip install emcee
    - python setup.py install

script:
    - cd tests
    - nosetests
